version: "3"

services:

  configuration-sdk-extensions-csharp-test:
    build: .
    container_name: configuration-sdk-extensions-csharp-test
    image: finbourne/configuration-sdk-extensions-csharp-test
    environment:
      - FBN_TOKEN_URL
      - FBN_USERNAME
      - FBN_PASSWORD
      - FBN_CLIENT_ID
      - FBN_CLIENT_SECRET
      - FBN_APP_NAME
      - FBN_CONFIGURATION_API_URL=${FBN_BASE_API_URL}/configuration
      - FBN_ACCESS_TOKEN
    volumes:
      - .:/usr/src